In [1]:
import keras
from keras.models import Sequential

Using TensorFlow backend.


In [2]:
from keras.layers.core import Dense, Dropout, Activation, Flatten

In [3]:
from keras.layers.convolutional import Convolution2D, MaxPooling2D

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
data = pd.read_csv('train.csv')

In [8]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [9]:
# data.iloc[3,1:].values.reshape(28,28).astype('uint8')

In [16]:
data.shape

(42000, 785)

In [10]:
df_x = data.iloc[:,1:].values.reshape(len(data),28,28,1)

In [19]:
df_x[0]

array([[[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
      

In [13]:
y = data.iloc[:,0].values

In [19]:
y

array([1, 0, 1, ..., 7, 6, 9])

In [14]:
df_y = keras.utils.to_categorical(y,num_classes = 10)

In [15]:
np.shape(df_y)

(42000, 10)

In [23]:
df_x.shape

(42000, 28, 28, 1)

In [20]:
x_train, x_test, y_train, y_test = train_test_split(df_x,df_y,test_size = 0.2,random_state = 4)

In [21]:
x_train

array([[[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]]],


       [[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],


In [22]:
np.shape(x_train)

(33600, 28, 28, 1)

In [25]:
model = Sequential()

In [26]:
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adadelta', metrics = ['accuracy'])

In [27]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               540900    
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
Total para

In [28]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs = 10)

Train on 33600 samples, validate on 8400 samples
Epoch 1/10
33600/33600 [==============================] - 24s 705us/step - loss: 7.9593 - acc: 0.5001 - val_loss: 3.8195 - val_acc: 0.7574
Epoch 2/10
33600/33600 [==============================] - 26s 767us/step - loss: 2.2392 - acc: 0.8508 - val_loss: 1.1910 - val_acc: 0.9183
Epoch 3/10
33600/33600 [==============================] - 23s 692us/step - loss: 1.1869 - acc: 0.9163 - val_loss: 0.7299 - val_acc: 0.9465
Epoch 4/10
33600/33600 [==============================] - 23s 683us/step - loss: 0.8432 - acc: 0.9373 - val_loss: 0.6038 - val_acc: 0.9562
Epoch 5/10
33600/33600 [==============================] - 25s 739us/step - loss: 0.6547 - acc: 0.9494 - val_loss: 0.4417 - val_acc: 0.9612
Epoch 6/10
33600/33600 [==============================] - 25s 733us/step - loss: 0.4958 - acc: 0.9567 - val_loss: 0.3332 - val_acc: 0.9681
Epoch 7/10
33600/33600 [==============================] - 26s 763us/step - loss: 0.3666 - acc: 0.9605 - val_loss: 0.2